project_id = "glsvoagtlaksuaimsppn"

[functions.seed-reviews]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.btc-check-payments]
verify_jwt = false

[functions.btc-check-payments.schedule]
enabled = true
cron = "*/60 * * * * *"

[functions.send-payment-confirmation]
verify_jwt = false